services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo?createDatabaseIfNotExist=true&useSSL=false&connectTimeout=10000&socketTimeout=10000&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_LIQUIBASE_ENABLED: "true"

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "/wait-for.sh mysql:3306 -- java -jar app.jar"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword" ]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge