spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    contexts: dev
    default-schema: todo
  thymeleaf:
    cache: false
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 10
server:
  port: 8080
logging:
  level:
    liquibase: DEBUG